// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[Table("Breed")]
public partial class Breed
{
    [Key]
    public int BreedID { get; set; }

    [Required]
    [Column("Breed")]
    [StringLength(100)]
    [Unicode(false)]
    public string Breed1 { get; set; }

    //[ForeignKey("BreedID")]
    //[InverseProperty("Breeds")]
    public virtual ICollection<Pet_Breed> Pet_Breeds { get; set; } = new List<Pet_Breed>();
}