// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[Table("Client")]
public partial class Client
{
    [Key]
    public int ClientID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string BankAccount { get; set; }

    [ForeignKey("ClientID")]
    [InverseProperty("Client")]
    public virtual User ClientNavigation { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Pet> Pets { get; set; } = new List<Pet>();
}