// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("ClinicID", "Location")]
[Table("Clinic_Location")]
public partial class Clinic_Location
{
    [Key]
    public int ClinicID { get; set; }

    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string Location { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Clinic_Locations")]
    public virtual Clinic Clinic { get; set; }
}