// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("ClinicID", "Phone")]
[Table("Clinic_Phone")]
public partial class Clinic_Phone
{
    [Key]
    public int ClinicID { get; set; }

    [Key]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Clinic_Phones")]
    public virtual Clinic Clinic { get; set; }
}