// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[Table("Pet")]
public partial class Pet
{
    [Key]
    public int PetID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(1000)]
    [Unicode(false)]
    public string Photo { get; set; }

    public int? AgeInMonth { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Sex { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string IDNoteBookImage { get; set; }

    public int UserID { get; set; }

    public bool ReadyForBreeding { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Other { get; set; }

    [InverseProperty("PetIDReceiverNavigation")]
    public virtual ICollection<Request_For_Breed> Request_For_BreedPetIDReceiverNavigations { get; set; } = new List<Request_For_Breed>();

    [InverseProperty("PetIDSenderNavigation")]
    public virtual ICollection<Request_For_Breed> Request_For_BreedPetIDSenderNavigations { get; set; } = new List<Request_For_Breed>();

    [InverseProperty("Pet")]
    public virtual ICollection<Reservation_For_Vaccine> Reservation_For_Vaccines { get; set; } = new List<Reservation_For_Vaccine>();

    [InverseProperty("Pet")]
    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    [ForeignKey("UserID")]
    [InverseProperty("Pets")]
    public virtual Client User { get; set; }

    [InverseProperty("Pet")]
    public virtual ICollection<Vaccine_Pet> Vaccine_Pets { get; set; } = new List<Vaccine_Pet>();

    //[ForeignKey("PetID")]
    [InverseProperty("Pet")]
    public virtual ICollection<Pet_Breed> Pet_Breeds { get; set; } = new List<Pet_Breed>();
}