// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("PetIDSender", "PetIDReceiver")]
[Table("Request_For_Breed")]
public partial class Request_For_Breed
{
    [Key]
    public int PetIDSender { get; set; }

    [Key]
    public int PetIDReceiver { get; set; }

    public bool Pair { get; set; }

    [ForeignKey("PetIDReceiver")]
    [InverseProperty("Request_For_BreedPetIDReceiverNavigations")]
    public virtual Pet PetIDReceiverNavigation { get; set; }

    [ForeignKey("PetIDSender")]
    [InverseProperty("Request_For_BreedPetIDSenderNavigations")]
    public virtual Pet PetIDSenderNavigation { get; set; }
}