// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("PetID", "ClinicID", "VaccineID", "Date")]
[Table("Reservation_For_Vaccine")]
public partial class Reservation_For_Vaccine
{
    [Key]
    public int PetID { get; set; }

    [Key]
    public int ClinicID { get; set; }

    [Key]
    public int VaccineID { get; set; }

    [Key]
    public DateOnly Date { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Reservation_For_Vaccines")]
    public virtual Clinic Clinic { get; set; }

    [ForeignKey("PetID")]
    [InverseProperty("Reservation_For_Vaccines")]
    public virtual Pet Pet { get; set; }

    [ForeignKey("VaccineID")]
    [InverseProperty("Reservation_For_Vaccines")]
    public virtual Vaccine Vaccine { get; set; }
}