// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("PetID", "ClinicID")]
[Table("Reservation")]
public partial class Reservation
{
    [Key]
    public int PetID { get; set; }

    [Key]
    public int ClinicID { get; set; }

    public DateTime? Date { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Reservations")]
    public virtual Clinic Clinic { get; set; }

    [ForeignKey("PetID")]
    [InverseProperty("Reservations")]
    public virtual Pet Pet { get; set; }
}