// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[Table("Secretary")]
[Index("ClinicID", Name = "UQ__Secretar__3347C2FC3AEFD065", IsUnique = true)]
public partial class Secretary
{
    [Key]
    public int SecretaryID { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Salary { get; set; }

    public DateOnly HiringDate { get; set; }

    public int? ClinicID { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Secretary")]
    public virtual Clinic Clinic { get; set; }

    [ForeignKey("SecretaryID")]
    [InverseProperty("Secretary")]
    public virtual User SecretaryNavigation { get; set; }
}