// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[Table("User")]
[Index("Email", Name = "UQ__User__A9D105341484EDF3", IsUnique = true)]
[Index("UserName", Name = "UQ__User__C9F28456FC8E532C", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Location { get; set; }

    public int? Age { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Sex { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Photo { get; set; }

    public int? RoleID { get; set; }

    [InverseProperty("ClientNavigation")]
    public virtual Client Client { get; set; }

    [InverseProperty("DoctorNavigation")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }

    [InverseProperty("SecretaryNavigation")]
    public virtual Secretary Secretary { get; set; }
}