// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("VaccineID", "ClinicID")]
[Table("Vaccine_Clinic")]
public partial class Vaccine_Clinic
{
    [Key]
    public int VaccineID { get; set; }

    [Key]
    public int ClinicID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("ClinicID")]
    [InverseProperty("Vaccine_Clinics")]
    public virtual Clinic Clinic { get; set; }

    [ForeignKey("VaccineID")]
    [InverseProperty("Vaccine_Clinics")]
    public virtual Vaccine Vaccine { get; set; }
}