// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PetBooK.DAL.Models;

[PrimaryKey("VaccineID", "PetID")]
[Table("Vaccine_Pet")]
public partial class Vaccine_Pet
{
    [Key]
    public int VaccineID { get; set; }

    [Key]
    public int PetID { get; set; }

    public double? Dose { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Time { get; set; }

    public bool IsVaccinated { get; set; }

    [ForeignKey("PetID")]
    [InverseProperty("Vaccine_Pets")]
    public virtual Pet Pet { get; set; }

    [ForeignKey("VaccineID")]
    [InverseProperty("Vaccine_Pets")]
    public virtual Vaccine Vaccine { get; set; }
}